---
- name: Install InfluxDB dependencies
  package:
    name: "{{ influxdb_dependencies }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2

- name: Add InfluxDB repository file [RHEL/CentOS]
  template:
    src: "{{ influxdb_yum_repo_template }}"
    dest: "/etc/yum.repos.d/{{ influxdb_yum_repo_template | basename | regex_replace('\\.j2$', '') }}"
    force: true
    backup: true
  when: ansible_pkg_mgr in ['yum', 'dnf']

- name: Install InfluxDB
  package:
    name: "{{ influxdb_package }}"
    state: "{{ (influxdb_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart influxdb
